//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yemek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Yemek()
        {
            this.Tbl_Yorum = new HashSet<Tbl_Yorum>();
        }
    
        public int Id { get; set; }
        public string Yemekad { get; set; }
        public string Resim { get; set; }
        public string icerik { get; set; }
        public Nullable<int> Kategoriid { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Malzemeler { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorum> Tbl_Yorum { get; set; }
    }
}
