//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tarifler
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Yemekad { get; set; }
        public string Resim { get; set; }
        public string Tarif { get; set; }
        public Nullable<int> Kategoriid { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
    }
}
